#include "Token.h"
namespace ztCompiler {
	//symbol table
	const std::unordered_map<std::string, TokenAttr> token::keyword_table{
			{ "char",TokenAttr::CHAR },
			{ "int",TokenAttr::INT },
			{ "switch",TokenAttr::SWITCH },
			{ "float",TokenAttr::FLOAT },
			{ "if",TokenAttr::IF },
			{ "char",TokenAttr::CHAR },
			{ "short",TokenAttr::SHORT },
			{ "double",TokenAttr::DOUBLE },
			{ "long",TokenAttr::LONG },
			{ "else",TokenAttr::ELSE },
			{ "int",TokenAttr::INT },
			{ "signed",TokenAttr::SIGNED },
			{ "unsigned",TokenAttr::UNSIGNED },
			{ "break",TokenAttr::BREAK },
			{ "bool",TokenAttr::BOOL },
			{ "case",TokenAttr::CASE },
			{ "complex",TokenAttr::COMPLEX },
			{ "const",TokenAttr::CONST },
			{ "restrict",TokenAttr::RESTRICT },
			{ "do",TokenAttr::DO },
			{"atomic",TokenAttr::ATOMIC},
			{ "volatile",TokenAttr::VOLATILE },
			{ "continue",TokenAttr::CONTINUE },
			{ "default",TokenAttr::DEFAULT },
			{ "while",TokenAttr::WHILE },
			{ "union",TokenAttr::UNION },
			{ "typedef",TokenAttr::TYPEDEF },
			{ "void",TokenAttr::VOID },
			{ "goto",TokenAttr::GOTO },
			{ "extern",TokenAttr::EXTERN },
			{ "auto",TokenAttr::AUTO },
			{ "static_assert",TokenAttr::STATIC_ASSERT },
			{ "thread_local",TokenAttr::THREAD_LOCAL },
	};

	const std::unordered_map<TokenAttr, const char*> lexical_table{
		{ TokenAttr::INT,"int"},
		{ TokenAttr::SHORT,"short"},
		{ TokenAttr::FLOAT,"float"},
		{ TokenAttr::UNSIGNED,"unsigned"},
		{ TokenAttr::LONG,"long"},
		{ TokenAttr::DOUBLE,"double"},
		{ TokenAttr::CHAR,"char"},
		{ TokenAttr::BOOL,"bool"},
		{ TokenAttr::AUTO,"" },
		{ TokenAttr::IF,"int" },
		{ TokenAttr::BREAK,"int" },
		{ TokenAttr::INLINE,"int" },
		{ TokenAttr::CONTINUE,"int" },
		{ TokenAttr::DEFAULT,"int" },
		{ TokenAttr::DO,"int" },
		{ TokenAttr::ELSE,"int" },
		{ TokenAttr::ENUM,"int" },
		{ TokenAttr::EXTERN,"int" },
		{ TokenAttr::FOR,"int" },
		{ TokenAttr::GOTO,"int" },
		{ TokenAttr::RESTRICT,"int" },
		{ TokenAttr::REGISTER,"int" },
		{ TokenAttr::RETURN,"int" },
		{ TokenAttr::SIZEOF,"int" },
		{ TokenAttr::STATIC,"int" },
		{ TokenAttr::STRUCT,"int" },
		{ TokenAttr::SWITCH,"int" },
		{ TokenAttr::TYPEDEF,"int" },
		{ TokenAttr::UNION,"int" },
		{ TokenAttr::INT,"int" },


		{ TokenAttr::ADD,"int" },
		{ TokenAttr::SUB,"int" },
		{ TokenAttr::MUL,"int" },
		{ TokenAttr::DIV,"int" },
		{ TokenAttr::LESS,"int" },
		{ TokenAttr::GREATER,"int" },
		{ TokenAttr::HASH,"int" },
		{ TokenAttr::DOUBLE_HASH,"int" },
		{ TokenAttr::DEC,"int" },
		{ TokenAttr::INC,"int" },
		{ TokenAttr::DEREF,"int" },
		{ TokenAttr::SUB_ASSIGN,"int" },
		{ TokenAttr::ADD_ASSIGN,"int" },
		{ TokenAttr::LEFT_SHIFT,"int" },
		{ TokenAttr::LEFT_EQUAL,"int" },
		{ TokenAttr::RIGHT_SHIFT,"int" },
		{ TokenAttr::RIGHT_EQUAL,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },

	};

}