#include "Token.h"
namespace ztCompiler {
	//symbol table
	const std::unordered_map<std::string, TokenAttr> token::keyword_table{
			{ "char",TokenAttr::CHAR },
			{ "int",TokenAttr::INT },
			{ "switch",TokenAttr::SWITCH },
			{ "float",TokenAttr::FLOAT },
			{ "if",TokenAttr::IF },
			{ "char",TokenAttr::CHAR },
			{ "short",TokenAttr::SHORT },
			{ "double",TokenAttr::DOUBLE },
			{ "long",TokenAttr::LONG },
			{ "else",TokenAttr::ELSE },
			{ "int",TokenAttr::INT },
			{ "signed",TokenAttr::SIGNED },
			{ "unsigned",TokenAttr::UNSIGNED },
			{ "break",TokenAttr::BREAK },
			{ "bool",TokenAttr::BOOL },
			{ "case",TokenAttr::CASE },
			{ "complex",TokenAttr::COMPLEX },
			{ "const",TokenAttr::CONST },
			{ "restrict",TokenAttr::RESTRICT },
			{ "do",TokenAttr::DO },
			{"atomic",TokenAttr::ATOMIC},
			{ "volatile",TokenAttr::VOLATILE },
			{ "continue",TokenAttr::CONTINUE },
			{ "default",TokenAttr::DEFAULT },
			{ "while",TokenAttr::WHILE },
			{ "union",TokenAttr::UNION },
			{ "typedef",TokenAttr::TYPEDEF },
			{ "void",TokenAttr::VOID },
			{ "goto",TokenAttr::GOTO },
			{ "extern",TokenAttr::EXTERN },
			{ "auto",TokenAttr::AUTO },
			{ "static_assert",TokenAttr::STATIC_ASSERT },
			{ "thread_local",TokenAttr::THREAD_LOCAL },
	};

	static const std::unordered_map<TokenAttr, const char*> lexical_table{
		{ TokenAttr::INT,"int"},
		{ TokenAttr::SHORT,"short"},
		{ TokenAttr::FLOAT,"float"},
		{ TokenAttr::UNSIGNED,"unsigned"},
		{ TokenAttr::LONG,"long"},
		{ TokenAttr::DOUBLE,"double"},
		{ TokenAttr::CHAR,"char"},
		{ TokenAttr::BOOL,"bool"},
		{ TokenAttr::AUTO,"auto" },
		{ TokenAttr::IF,"if" },
		{ TokenAttr::BREAK,"break" },
		{ TokenAttr::INLINE,"inline" },
		{ TokenAttr::CONTINUE,"continue" },
		{ TokenAttr::DEFAULT,"default" },
		{ TokenAttr::DO,"do" },
		{ TokenAttr::ELSE,"else" },
		{ TokenAttr::ENUM,"enum" },
		{ TokenAttr::EXTERN,"extern" },
		{ TokenAttr::FOR,"for" },
		{ TokenAttr::GOTO,"goto" },
		{ TokenAttr::RESTRICT,"restrict" },
		{ TokenAttr::REGISTER,"register" },
		{ TokenAttr::RETURN,"return" },
		{ TokenAttr::SIZEOF,"sizeof" },
		{ TokenAttr::STATIC,"static" },
		{ TokenAttr::STRUCT,"struct" },
		{ TokenAttr::SWITCH,"switch" },
		{ TokenAttr::TYPEDEF,"typedef" },
		{ TokenAttr::UNION,"union" },
		

		{ TokenAttr::PLUS,"+" },
		{ TokenAttr::SUB,"-" },
		{ TokenAttr::MUL,"*" },
		{ TokenAttr::DIV,"int" },
		{ TokenAttr::LESS,"int" },
		{ TokenAttr::GREATER,"int" },
		{ TokenAttr::HASH,"int" },
		{ TokenAttr::DOUBLE_HASH,"int" },
		{ TokenAttr::DEC,"int" },
		{ TokenAttr::INC,"int" },
		{ TokenAttr::DEREF,"int" },
		{ TokenAttr::SUB_ASSIGN,"int" },
		{ TokenAttr::ADD_ASSIGN,"int" },
		{ TokenAttr::LEFT_SHIFT,"int" },
		{ TokenAttr::LEFT_EQUAL,"int" },
		{ TokenAttr::RIGHT_SHIFT,"int" },
		{ TokenAttr::RIGHT_EQUAL,"int" },
		{ TokenAttr::EQUAL,"int" },
		{ TokenAttr::NOT_EQUAL ,"int" },
		{ TokenAttr::LOGICAL_AND,"int" },
		{ TokenAttr::AND_ASSIGN,"int" },
		{ TokenAttr::INT,"int" },
		{ TokenAttr::INT,"int" },

	};

}